---
name: poolboy-publish-workflow
on:
- push:
    tags:
    - v[0-9]*
jobs:
  build:
    if: github.repository == 'redhat-cop/poolboy'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF#refs/tags/})
    - name: Publish My Image to Quay
      uses: elgohr/Publish-Docker-Github-Action@2.11
      with:
        name: redhat-cop/poolboy
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io
        context: operator
        dockerfile: operator/Dockerfile
        tags: ${{ format('latest,{0}', steps.get_version.outputs.VERSION) }}
