---
# test2
name: poolboy-publish-workflow
on:
  push:
    branches:
    # Build latest off of master
    - master
    tags:
    # Version tag glob match, start 'v' then a number then whatever.
    - v[0-9]*
jobs:
  build:
    # Prevent build failures on forks
    if: github.repository == 'jkupferer/poolboy'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Show GITHUB_REF
      run: echo ${GITHUB_REF}
    - name: Get the version
      id: get_version
      run: |
        echo -n ::set-output name=IMAGE_TAGS::
        # Tags build from master as latest
        if [ "${GITHUB_REF}" == 'heads/master' ]; then
            echo latest
        # Match git tags to image tags
        elif [ "${GITHUB_REF:0:10}" == 'refs/tags/' ]; then
            echo "${GITHUB_REF:10}"
        # Otherwise, best guess...
        else
            echo "${GITHUB_REF/*\//}"
        fi
    - name: Show IMAGE_TAGS
      run: echo WTF ${{ steps.get_version.outputs.IMAGE_TAGS }}

    #- name: Publish My Image to Quay
    #  uses: elgohr/Publish-Docker-Github-Action@master
    #  with:
    #    # This quay repository name matches github repository name
    #    name: ${{ github.repository }}
    #    username: ${{ secrets.QUAY_USERNAME }}
    #    password: ${{ secrets.QUAY_PASSWORD }}
    #    registry: quay.io
    #    context: operator
    #    dockerfile: operator/Dockerfile
    #    tags: ${{ steps.get_version.outputs.IMAGE_TAGS }}
